<?php
namespace Bga\Games\DeadMenTellNoTales;

use Bga\Games\DeadMenTellNoTales\Game;
use BgaUserException;

class DMTNT_TileData
{
    public function getData(): array
    {
        return [
            'tile-back' => [
                'type' => 'back',
                'deck' => 'tile',
            ],
            'dinghy' => [
                'type' => 'deck',
                'deck' => 'tile',
                'color' => 'both',
                'touchPoints' => [0],
            ],
            'tracker' => [
                'type' => 'deck',
                'deck' => 'tile',
                'startX' => 0,
                'startY' => -1,
                'color' => 'both',
                'touchPoints' => [0],
                'starter' => true,
            ],
            'tile001' => [
                'type' => 'deck',
                'deck' => 'tile',
                'startX' => 0,
                'startY' => 0,
                'fire' => false,
                'color' => 'yellow',
                'touchPoints' => [0, 1, 2, 3],
                'starter' => true,
            ],
            'tile002' => [
                'type' => 'deck',
                'deck' => 'tile',
                'startX' => -1,
                'startY' => 0,
                'fire' => false,
                'color' => 'red',
                'touchPoints' => [0, 1, 3],
                'starter' => true,
            ],
            'tile003' => [
                'type' => 'deck',
                'deck' => 'tile',
                'startX' => 1,
                'startY' => 0,
                'fire' => false,
                'color' => 'red',
                'touchPoints' => [0, 1, 3],
                'starter' => true,
            ],
            'tile004' => [
                'type' => 'deck',
                'deck' => 'tile',
                'startX' => 0,
                'startY' => 1,
                'fire' => false,
                'color' => 'yellow',
                'startsWith' => 'trapdoor',
                'touchPoints' => [0, 1, 2, 3],
                'starter' => true,
            ],
            'tile005' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 3,
                'color' => 'red',
                'barrel' => 5,
                'touchPoints' => [0, 1, 2, 3],
            ],
            'tile006' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 4,
                'color' => 'red',
                'touchPoints' => [0, 1, 2, 3],
            ],
            'tile007' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 4,
                'color' => 'yellow',
                'touchPoints' => [0, 1, 2, 3],
            ],
            'tile008' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 2,
                'color' => 'yellow',
                'barrel' => 4,
                'touchPoints' => [2],
            ],
            'tile009' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 4,
                'color' => 'yellow',
                'touchPoints' => [1, 2],
            ],
            'tile010' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 1,
                'color' => 'yellow',
                'barrel' => 3,
                'touchPoints' => [2, 3],
            ],
            'tile011' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 2,
                'color' => 'yellow',
                'touchPoints' => [1, 2],
            ],
            'tile012' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 3,
                'color' => 'red',
                'barrel' => 5,
                'touchPoints' => [2, 3],
            ],
            'tile013' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 1,
                'color' => 'red',
                'barrel' => 3,
                'touchPoints' => [1, 2, 3],
            ],
            'tile014' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 1,
                'color' => 'yellow',
                'touchPoints' => [1, 2, 3],
            ],
            'tile015' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 2,
                'color' => 'red',
                'barrel' => 4,
                'touchPoints' => [1, 2, 3],
            ],
            'tile016' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 3,
                'color' => 'red',
                'touchPoints' => [1],
            ],
            'tile017' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 0,
                'color' => 'yellow',
                'barrel' => 2,
                'touchPoints' => [0, 2, 3],
            ],
            'tile018' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 3,
                'color' => 'yellow',
                'touchPoints' => [1, 2, 3],
            ],
            'tile019' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 4,
                'color' => 'red',
                'touchPoints' => [0, 1, 2],
            ],
            'tile020' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 4,
                'color' => 'red',
                'touchPoints' => [0, 1, 3],
            ],
            'tile021' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 2,
                'color' => 'red',
                'touchPoints' => [1, 3],
            ],
            'tile022' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 0,
                'color' => 'red',
                'barrel' => 2,
                'touchPoints' => [0, 2, 3],
            ],
            'tile023' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 2,
                'color' => 'yellow',
                'touchPoints' => [0, 2, 3],
            ],
            'tile024' => [
                'type' => 'deck',
                'deck' => 'tile',
                'fire' => 3,
                'color' => 'yellow',
                'touchPoints' => [1, 3],
            ],
        ];
    }
}
